# Generated by Django 3.1.7 on 2021-04-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nasabah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nasabah', models.CharField(max_length=16)),
                ('nama', models.CharField(max_length=60)),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('usia', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
