# Generated by Django 3.1.7 on 2021-04-17 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nasabah', '0002_auto_20210417_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasabah',
            name='dateAuthenticate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nasabah',
            name='date_register',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nasabah',
            name='isAuthenticate',
            field=models.BooleanField(default=False),
        ),
    ]
